[features]
seeds = false
skip-lint = false
[programs.localnet]
fundme = "49wKh7f9yc7qtch5upj52EA4dUqKNSVFb2Pm7SMVUbFH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/macbookpro/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
